language: node_js
node_js:
  - "node"
  - "10"
  - "8"
  - "6"
before_install:
  - yarn global add grunt-cli
  - yarn global add karma-cli
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - eval `ssh-agent -s`
  - '[ -n "$GITHUB_SSH_KEY" ] && echo "$GITHUB_SSH_KEY" | base64 -d | ssh-add - || true'
install: yarn --frozen-lockfile
script: grunt test-ci -v
sudo: false
env:
  global:
    - secure: MUB0jpyCJiYqrXQS6cwtLv1jyaDR30naRyHDBu+tLoyZNBTRWvlwrW75SvKEVwFI0JWqgUKRcwixsQFKRnKhZe+nD5zC56hxTtZc7Zw7m+mwpLHFJg5tfw8OAimd1Bvku9g0mig2kvjipxSsOMQsqXC7WfqESrTD2NMVdymp/ik=
    - secure: 0nJbWUF7NqGrDzX2de7SUx0YyHd0n2IXNmKIYRktEQiKe1omqeXi5SfIMzCHSmUGX3Ez2F2L5cVDbwob3pydFcK7KxpHp4JhW71JXis1sFvvaNR9lRglL7IFYRsqZz25esJlzS44B+Qr3mQCZLz77liDSX3mnmLmy14XECgB+DE=
